### ISSUE TITLE
Печать первичного осмотра

### ISSUE THREAD

**Issue by Koroleva63** [tetarenko/hospital#20]
Приложение не открывает страницу печати первичного осмотра ни в разделе Первичный осмотра, ни в разделе Печать.

**Comment by tetarenko** [comment]
Исправлю

**Comment by tetarenko** [comment]
Исправлено

**Comment by Koroleva63** [comment]
Печать первичного осмотра не идет. Пустая форма печатается. После заполнения данными - печатная форма первичного осмотра не формируется. 
![image](https://user-images.githubusercontent.com/32264934/37902790-3afbc27a-30fe-11e8-81da-9c4b58feacff.png)

**Comment by Koroleva63** [comment]
см. ИБ 111

**Comment by tetarenko** [comment]
Подправил
