### ISSUE TITLE
Вопросы к разделам Первичного осмотра

### ISSUE THREAD

**Issue by Koroleva63** [tetarenko/hospital#21]
При заполнении полей Первичного осмотра можно выбрать/отметить все предлагаемые значения в пунктах: Перкуторно звуки, Аускультативно дыхание, Тоны. см. ИБ 777.  Пастозность, отеки  - наверно правильно. Отеков может быть много. Тоны они есть или их нет.

**Comment by tetarenko** [comment]
ок, исправлю

**Comment by tetarenko** [comment]
Исправлено
