### ISSUE TITLE
Печать выписного эпикриза (авто)

### ISSUE THREAD

**Issue by Koroleva63** [tetarenko/hospital#23]
В разделе Выписной эпикриз - Просмотр кнопка изменить активна. В этом режиме можно внести изменения и сохранить их. Вроде в ТЗ авто просто отражает внесенные изменения в ИБ, А Эпикриз ЛB  служит для корректировки эпикриза. В настоящее время эти пункты практически одинаковы. И в том и в другом можно вносить ручные правки. Я не в курсе особенно как хотел Заказчик. Проверьте реализацию.

**Comment by Koroleva63** [comment]
Это связано с ошибкой печати первичного осмотра?

**Comment by tetarenko** [comment]
Цитирую ТЗ

3. Выписной эпикриз
3.1 Выписной эпикриз формируется автоматически на основе данных ИБ.
3.2 ЛВ может отредактировать любое поле Выписного эпикриза и распечатать его.
3.3 В БД сохраняется автоматически сгенерированная версия. Эта версия автоматически обновляется при изменении любых полях данных ИБ. Эта версия доступна по команде (кнопке) «Автоматический выписной эпикриз».
3.4 Выписной эпикриз, в который ЛВ внес свои изменения/дополнения и отправил на печать также автоматически сохраняется и доступен для просмотра и редактирования по команде (кнопке) «Дополненный выписной эпикриз».
3.5 В БД хранится только самая последняя версия дополненного выписного эпикриза, которая образовалась в результате модификации автоматически сгенерированного либо ранее сохраненного дополненного выписного эпикриза.

**Comment by Koroleva63** [comment]
в режиме  Выписной эпикриз авто можно внести изменения или нет? По ТЗ  я  понимаю, что нет. В приложении кнопка Изменить активна и изменения сохраняются. 
![image](https://user-images.githubusercontent.com/32264934/37907754-ae22416a-310e-11e8-8952-a49de3699a09.png)
