### ISSUE TITLE
Печатная форма мед. карты  - стр. 1 и стр. 2

### ISSUE THREAD

**Issue by Koroleva63** [tetarenko/hospital#25]
В печатной форме после пункта 11 Диагноз при поступлении отсутствуют пункты Диагноз клинический, дата установления  и пункт  Диагноз заключительный клинический (основной, осложнение основного, сопутствующий. 
В исходном документе нумерация пунктов тоже с ошибкой. Мое мнение д.б. следующая нумерация: 
1. ФИО 2. ПОЛ 3 Возраст  4. Постоянное место жительства и в этом пункте Паспорт, полис
5. Место работы 6. Кем направлен 7. Доставлен в стационар по экстр показателям  8. Диагноз направившего учреждения 
9. Диагноз при поступлении 10. Диагноз клинический  Дата установления 
11 Диагноз заключительный  а) основой, б) осложнение основного в) сопутствующий 
12. Госпитализирован в данном году  по поводу данного заболевания 
13 хирургические операции, методы обезболивания 
14 Другие  виды лечения 
Для больных  злокачественными новообразованиями - 1 . Специальное лечение: хирургическое ...., 2. Паллиативное 3 . Симптоматическое 
15. Отметка  о выдаче листа нетрудоспособности ......  
.......
20. С режимом нахождения  в больнице ознакомлен(а) 
Лечащий врач                                                        Зав. отделением 
подпись                                                                       подпись 

Если есть сканы исходных документов то в соответствии с ними и надо делать разметку Мед карты:
1 страница:  шапка, наименование учреждения  - ЛРБ №2  пункты  1 - 10
2 страница: п. 11 - 20  с подписями Лечащего врача  и Зав. отделения, 
3. страница  - это уже данные первичного осмотра

**Comment by Koroleva63** [comment]
в п. 14  специальное лечение: гамма-терапия пишется через дефис.

**Comment by Koroleva63** [comment]
На самом деле странная нумерация. Даже удивляюсь как это так я могла такое нагородить. оформляла по образцу и официальной форме. Конечно все пункты по порядку . Извините, пжл. 
1. ФИО 
2. ПОЛ 
3 Возраст
4. Постоянное место жительства и в этом пункте Паспорт, полис
5. Место работы.  
6. Кем направлен 
7. Доставлен в стационар по экстр показателям 
8. Диагноз направившего учреждения
9. Диагноз при поступлении 
10. Диагноз клинический Дата установления
11 Диагноз заключительный а) основой, б) осложнение основного в) сопутствующий
12. Госпитализирован в данном году по поводу данного заболевания
13. хирургические операции, методы обезболивания
14 Другие виды лечения
Для больных злокачественными новообразованиями - 1 . Специальное лечение: хирургическое ...., 2. Паллиативное 3 . Симптоматическое
15. Отметка о выдаче листа нетрудоспособности ......
.......
20. С режимом нахождения в больнице ознакомлен(а)
Лечащий врач Зав. отделением
подпись               подпись

**Comment by tetarenko** [comment]
Исправил, будет в следующей версии с общими исправлениями
