### ISSUE TITLE
Мед. карта - печатная форма первичного осмотра

### ISSUE THREAD

**Issue by Koroleva63** [tetarenko/hospital#27]
На стр. 3 должен печататься Первичный осмотр и далее Объективное обследование на последующих страницах.
Нет полей (выверка по требованию врача) 
Сознание:  4 значения (в сознании, оглушение, сопор, кома)
чсс
пульс
Мочеиспускание: свободное, затруднено

**Comment by tetarenko** [comment]
Закрываю, так как решили, что по пожеланиям врача поля не нужны

**Comment by tetarenko** [comment]
Исправлено, будет с обновлением
