### ISSUE TITLE
Ввод показателей АД 

### ISSUE THREAD

**Issue by Koroleva63** [tetarenko/hospital#28]
Давление верхнее/нижнее. В поле АД можно ввести только одно значение.  Через слеш не получается., т.е как бы ни старалась второе значение не вводиться.

**Comment by Koroleva63** [comment]
Получилось ввести в таком формате 180.50  Вообще-то вводится через слеш 180.50

**Comment by tetarenko** [comment]
принято

**Comment by Koroleva63** [comment]
исправлено
