### ISSUE TITLE
Форма  Первичный осмотр

### ISSUE THREAD

**Issue by Koroleva63** [tetarenko/hospital#29]
1.  Живот: два раза безболезнеенный: безболезненный и безболезненный (где) ????? 
безболезненный (где) ?????  заменить на болезненный (где). 
2. Это просто так : в полях Сознание: В сознании, Оглушение, Сопор, Кома. Написаны с большой буквы,  Это же не трудно исправить. 
3. В печатной форме пропущены: Сознание и Лимфоузлы. В форме ввода  - есть.

**Comment by Koroleva63** [comment]
в печатной форме Первичного осмотра  - посмотри формат времени 2:37 . а в форме ввода - 14:37

**Comment by tetarenko** [comment]
принято

**Comment by Koroleva63** [comment]
функцию времени проверить во всех разделах. В эпикризе - время выписки. 
В мед карте - главная страница: см. время поступления и время выписки - одинаково. На самом деле оно разное: 
ИБ 3333 время поступления - 1:15, время выписки - 15:39. 
![image](https://user-images.githubusercontent.com/32264934/38198314-ef39640e-3694-11e8-9e35-e617ae372a35.png)

**Comment by Koroleva63** [comment]
Даты правда я ввела не соблюдая последовательность, но проверки же нет.

**Comment by Koroleva63** [comment]
В Лечении время операции тоже в не том формате. Т.е. проверить все разделы. мед карты и эпикриза.
