### ISSUE TITLE
Страница авторизации полностью не отображается 

### ISSUE THREAD

**Issue by Koroleva63** [tetarenko/hospital#31]
Загружалась с не рабочего компьютера, а  с домашнего. Страница авторизации полностью не отображается. В чем  может быть проблема.?

**Comment by Koroleva63** [comment]
![image](https://user-images.githubusercontent.com/32264934/38243179-5c1a4dfe-373f-11e8-83f3-7e0a96deac7d.png)

**Comment by tetarenko** [comment]
поправил
